### ISSUE TITLE
Toggle Crime - Select "all Crimes" should not sum up with other crime types

### ISSUE THREAD

**Issue by MatthiasKraus** [FabianSperrle/InfoVisII#3]
Aggregated Map: all crimes wird mit anderen crimes aggregiert - wenn all crimes selected ist, sollte das an und abwählen von anderen crimes keine auswirkungen haben

**Comment by FabianSperrle** [comment]
Fixed in 02d3acdf399e533b065ad09b24462b55ff827dd4
