### ISSUE TITLE
LSOA regions not separated?

### ISSUE THREAD

**Issue by FabianSperrle** [FabianSperrle/InfoVisII#4]
There are multiple regions on the map that look like they should be divided in wards, but are not. 

![wards](https://cloud.githubusercontent.com/assets/1345257/16261856/884edcaa-386d-11e6-97f8-67d16976db9d.png)

**Comment by MatthiasKraus** [comment]
https://en.wikipedia.org/wiki/Wards_of_the_City_of_London#/media/File:City_of_London_UK_labelled_ward_map_2003.svg
nein die sind so komisch eingeteilt... die spinnen die britten(:

**Comment by FabianSperrle** [comment]
... okay. 

:smiley:
