### ISSUE TITLE
toggleAll areas, activate 1 -> crash

### ISSUE THREAD

**Issue by MatthiasKraus** [FabianSperrle/InfoVisII#5]
numeric.min.js:1 Uncaught Error: numeric: eigenvalue iteration does not converge -- increase maxiter?numeric.QRFrancis @ numeric.min.js:1numeric.eig @ numeric.min.js:1AOE @ corrplot.min.js:2load @ corrplot.js:138calculateCorrelationMatrix @ corrplot.js:107n.emit @ telegraph.min.js:3DataController.filterDate @ dataController.js:242DataController.dateChangeBoth @ dataController.js:231(anonymous function) @ crimeTimeViews.js:795(anonymous function) @ d3.v3.min.js:1
detailPanel.js:798 doshit

**Comment by FabianSperrle** [comment]
This is due to the correlation matrix.
Possible fix: don't update matrix when selection is empty.
